// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAYLHQOkzBeXHaXJhJSQu7Wq3EJMHFEdI',
    appId: '1:227552046711:web:8053e86db3cbada0816072',
    messagingSenderId: '227552046711',
    projectId: 'piscine-mobile-04',
    authDomain: 'piscine-mobile-04.firebaseapp.com',
    storageBucket: 'piscine-mobile-04.appspot.com',
    measurementId: 'G-KZJ8BNJJRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOM4j92gADGVgw8N7jWNnHsAuEHtiYYs8',
    appId: '1:227552046711:android:c2bb3242fb74a0ad816072',
    messagingSenderId: '227552046711',
    projectId: 'piscine-mobile-04',
    storageBucket: 'piscine-mobile-04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATnJ_aKF4WIpU05cYCq7zDyfxgqABYdrI',
    appId: '1:227552046711:ios:d3f78baa41d8bb33816072',
    messagingSenderId: '227552046711',
    projectId: 'piscine-mobile-04',
    storageBucket: 'piscine-mobile-04.appspot.com',
    iosClientId: '227552046711-nd0fv7a75e00fqhqd3i541s2tni3v9iv.apps.googleusercontent.com',
    iosBundleId: 'com.example.module04',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATnJ_aKF4WIpU05cYCq7zDyfxgqABYdrI',
    appId: '1:227552046711:ios:cd7204423a0c71d6816072',
    messagingSenderId: '227552046711',
    projectId: 'piscine-mobile-04',
    storageBucket: 'piscine-mobile-04.appspot.com',
    iosClientId: '227552046711-873149eq602i6247t48avjlbpci76sfl.apps.googleusercontent.com',
    iosBundleId: 'com.example.module04.RunnerTests',
  );
}
